name: Run Shell Script and Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode Google Service Account Key
        run: |
          set -x
          ENCODED_SECRET=$(echo -n '${{ secrets.GOOGLE_SA_KEY }}' | base64 | tr -d '\n')
          echo "ENCODED_SECRET=$ENCODED_SECRET" >> $GITHUB_ENV
        shell: bash

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Dashboard Docker image
        run: |
            docker build -t data-extraction .

      - name: Tag and push Dashboard image
        run: |
          docker tag data-extraction:latest ${{ secrets.DOCKERHUB_USERNAME }}/data-extraction:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/data-extraction:latest

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GOOGLE_SA_KEY }}
          project_id: nxgenailab

      - name: Deploy React app to Google Cloud Storage
        run: |
          gcloud run deploy data-extraction \
          --image=${{ secrets.DOCKERHUB_USERNAME }}/data-extraction:latest \
          --platform=managed \
          --region=us-east1 \
          --allow-unauthenticated \
        shell: bash
