[theme]
primaryColor = "#5C6AC4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F6F7"
textColor = "#202223"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
